//! # MDB Notification System
//!
//! Built-in notification daemon for MDB Desktop. Implements the
//! freedesktop.org Desktop Notifications Specification so that
//! standard `notify-send` and app notifications work out of the box.
//!
//! Notifications are rendered as translucent overlays in the top-right
//! corner, stacking downward. They support:
//!
//! - Title + body text
//! - App icon
//! - Action buttons
//! - Urgency levels (low, normal, critical)
//! - Expiration timeouts
//! - MDB-specific notifications (fold events, dimensional warnings, etc.)
//!
//! ## MDB Integration
//!
//! Special MDB notifications are generated by:
//! - Process fold/unfold events
//! - MDBFS mount/unmount
//! - Dimensional evolution milestones
//! - Experiment framework completions

use std::collections::VecDeque;
use std::time::{Duration, Instant};

/// Notification urgency level.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Urgency {
    /// Low urgency — brief display, no sound.
    Low,
    /// Normal urgency — standard display.
    Normal,
    /// Critical urgency — persistent until dismissed, optional sound.
    Critical,
}

/// A notification action (button).
#[derive(Debug, Clone)]
pub struct NotificationAction {
    /// Action key (sent back to the app on click).
    pub key: String,
    /// Display label.
    pub label: String,
}

/// A single notification.
#[derive(Debug, Clone)]
pub struct Notification {
    /// Unique ID for this notification.
    pub id: u32,
    /// App name.
    pub app_name: String,
    /// Summary (title) text.
    pub summary: String,
    /// Body text (may contain simple markup).
    pub body: String,
    /// Icon name or path.
    pub icon: Option<String>,
    /// Urgency level.
    pub urgency: Urgency,
    /// When this notification was created.
    pub created_at: Instant,
    /// How long to display (None = use default).
    pub timeout: Option<Duration>,
    /// Available actions.
    pub actions: Vec<NotificationAction>,
    /// Whether this notification has been read/dismissed.
    pub dismissed: bool,
    /// Whether this is an MDB system notification.
    pub is_mdb: bool,
    /// MDB-specific category (for filtering).
    pub mdb_category: Option<MdbNotificationCategory>,
}

/// Categories for MDB system notifications.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum MdbNotificationCategory {
    /// Process was folded.
    ProcessFolded,
    /// Process was unfolded.
    ProcessUnfolded,
    /// MDBFS mounted.
    FsMounted,
    /// MDBFS unmounted.
    FsUnmounted,
    /// Evolution milestone reached.
    EvolutionMilestone,
    /// Experiment completed.
    ExperimentComplete,
    /// Experiment failed.
    ExperimentFailed,
    /// Security event.
    SecurityEvent,
}

/// The notification daemon.
pub struct NotificationDaemon {
    /// All active (undismissed) notifications, newest first.
    notifications: VecDeque<Notification>,
    /// Notification history (dismissed).
    history: Vec<Notification>,
    /// Next notification ID.
    next_id: u32,
    /// Maximum active notifications to display at once.
    pub max_visible: usize,
    /// Default timeout for normal urgency.
    pub default_timeout: Duration,
    /// Default timeout for low urgency.
    pub low_timeout: Duration,
    /// Whether the notification center is open (shows history).
    pub center_open: bool,
    /// Maximum history size.
    pub max_history: usize,
    /// Whether to suppress low-urgency notifications (Do Not Disturb).
    pub dnd_mode: bool,
}

impl NotificationDaemon {
    pub fn new() -> Self {
        Self {
            notifications: VecDeque::new(),
            history: Vec::new(),
            next_id: 1,
            max_visible: 5,
            default_timeout: Duration::from_secs(5),
            low_timeout: Duration::from_secs(3),
            center_open: false,
            max_history: 100,
            dnd_mode: false,
        }
    }

    /// Push a new notification. Returns the assigned ID.
    pub fn notify(
        &mut self,
        app_name: String,
        summary: String,
        body: String,
        icon: Option<String>,
        urgency: Urgency,
        timeout: Option<Duration>,
        actions: Vec<NotificationAction>,
    ) -> u32 {
        // In DND mode, suppress everything except critical
        if self.dnd_mode && urgency != Urgency::Critical {
            let id = self.next_id;
            self.next_id += 1;
            // Still add to history
            self.add_to_history(Notification {
                id,
                app_name,
                summary,
                body,
                icon,
                urgency,
                created_at: Instant::now(),
                timeout,
                actions,
                dismissed: true,
                is_mdb: false,
                mdb_category: None,
            });
            return id;
        }

        let id = self.next_id;
        self.next_id += 1;

        let notification = Notification {
            id,
            app_name,
            summary,
            body,
            icon,
            urgency,
            created_at: Instant::now(),
            timeout,
            actions,
            dismissed: false,
            is_mdb: false,
            mdb_category: None,
        };

        log::info!("Notification {}: {} — {}", id, notification.summary, notification.body);
        self.notifications.push_front(notification);

        // Trim if too many active
        while self.notifications.len() > self.max_visible * 2 {
            if let Some(old) = self.notifications.pop_back() {
                self.add_to_history(old);
            }
        }

        id
    }

    /// Push an MDB system notification.
    pub fn notify_mdb(
        &mut self,
        category: MdbNotificationCategory,
        summary: String,
        body: String,
    ) -> u32 {
        let urgency = match category {
            MdbNotificationCategory::SecurityEvent => Urgency::Critical,
            MdbNotificationCategory::ExperimentFailed => Urgency::Normal,
            _ => Urgency::Low,
        };

        let id = self.notify(
            "MDB-OS".to_string(),
            summary,
            body,
            Some("mdb-logo".to_string()),
            urgency,
            None,
            vec![],
        );

        // Tag it as MDB
        if let Some(n) = self.notifications.front_mut() {
            n.is_mdb = true;
            n.mdb_category = Some(category);
        }

        id
    }

    /// Dismiss a notification by ID.
    pub fn dismiss(&mut self, id: u32) {
        if let Some(pos) = self.notifications.iter().position(|n| n.id == id) {
            let mut n = self.notifications.remove(pos).unwrap();
            n.dismissed = true;
            self.add_to_history(n);
        }
    }

    /// Dismiss all active notifications.
    pub fn dismiss_all(&mut self) {
        while let Some(mut n) = self.notifications.pop_front() {
            n.dismissed = true;
            self.add_to_history(n);
        }
    }

    /// Tick — expire old notifications.
    pub fn tick(&mut self) {
        let now = Instant::now();
        let mut expired_ids = Vec::new();

        for n in self.notifications.iter() {
            if n.urgency == Urgency::Critical {
                continue; // Critical notifications don't auto-expire
            }
            let timeout = n.timeout.unwrap_or(match n.urgency {
                Urgency::Low => self.low_timeout,
                Urgency::Normal => self.default_timeout,
                Urgency::Critical => Duration::from_secs(0), // unreachable
            });
            if now.duration_since(n.created_at) >= timeout {
                expired_ids.push(n.id);
            }
        }

        for id in expired_ids {
            self.dismiss(id);
        }
    }

    /// Get all visible (active, undismissed) notifications.
    pub fn visible(&self) -> impl Iterator<Item = &Notification> {
        self.notifications.iter().take(self.max_visible)
    }

    /// Get notification history.
    pub fn history(&self) -> &[Notification] {
        &self.history
    }

    /// Clear history.
    pub fn clear_history(&mut self) {
        self.history.clear();
    }

    /// Toggle Do Not Disturb mode.
    pub fn toggle_dnd(&mut self) {
        self.dnd_mode = !self.dnd_mode;
        log::info!("Do Not Disturb: {}", if self.dnd_mode { "ON" } else { "OFF" });
    }

    /// Toggle notification center.
    pub fn toggle_center(&mut self) {
        self.center_open = !self.center_open;
    }

    /// Get count of unread notifications.
    pub fn unread_count(&self) -> usize {
        self.notifications.len()
    }

    fn add_to_history(&mut self, notification: Notification) {
        self.history.push(notification);
        if self.history.len() > self.max_history {
            self.history.remove(0);
        }
    }
}
